name: Build
on: push
jobs:
  test:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        erlang_version:
        - "23.2"
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2
    - name: CONFIGURE OTP & ELIXIR
      uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.erlang_version }}
        elixir-version: 1.10.4
    - name: CONFIGURE BAZEL
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        cat << EOF >> .bazelrc
          build --@bazel-erlang//:erlang_version=${{ matrix.erlang_version }}
          build --@bazel-erlang//:erlang_home=${ERLANG_HOME}
        EOF
    #! - name: Setup tmate session
    #!   uses: mxschmitt/action-tmate@v3
    - name: BUILD
      run: |
        bazelisk build :bazel_erlang_lib
